apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: yhu4rvhgt-go 
  janus-idp.io/tekton: yhu4rvhgt-go
  backstage.io/kubernetes-id: yhu4rvhgt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yhu4rvhgt-go
resources:
  - ci-tekton.yaml
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml