apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: yhu4rvhgt-go
  janus-idp.io/tekton: yhu4rvhgt-go
  backstage.io/kubernetes-id: yhu4rvhgt-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: yhu4rvhgt-go
resources:
- deployment.yaml
- route.yaml
- service.yaml
